### ISSUE TITLE
WebUI configuration

### ISSUE THREAD

**Issue by micheliknechtel** [R0GGER/mistserver#3]
Hi Roger,

I got your project and is working fine, but I would like to create a docker image with my streaming configuration, without passing by the web UI... I tried to find the place where it is storage in linux and I'm also struggling with the Api ... So could you give me a hand with that ?

Thanks

**Comment by R0GGER** [comment]
Hello Micheli,

Sorry I have limited knowlegde of the Mistserver API, I haven't used it much. Please go to https://github.com/DDVTECH/mistserver, the official mistserver source repository and ask them.
I just updated the mistserver-image to Mistserver v3.0, which is the full version of MistServer (Pro) because they chose to make Mistserver fully Open Source!

Mistserver 3.0 Changelog:
https://releases.mistserver.org/changelog

Read more:
https://news.mistserver.org/news/108/Release+notes+summary+3.0
https://news.mistserver.org/news/106/Why+is+all+of+MistServer+open+source%3F

Good luck!

Rogger
